# Generated by Django 3.2.13 on 2023-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='收藏')),
                ('co_down_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='收藏地址')),
            ],
            options={
                'verbose_name': '收藏列表',
                'verbose_name_plural': '收藏列表',
                'db_table': 'Colect',
            },
        ),
        migrations.CreateModel(
            name="Douyin",
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ('vedioname',models.CharField(blank=True,max_length=255,null=True,verbose_name="视频标题")),
                ('username',models.CharField(blank=True,max_length=255,null=True,verbose_name="评论用户")),
                ('comment',models.CharField(blank=True,max_length=255,null=True,verbose_name="评论内容")),
                ('url',models.CharField(blank=True,max_length=255,null=True,verbose_name='内容详情'))
            ],
            options={
                'verbose_name': '抖音数据',
                'verbose_name_plural': '抖音数据',
                'db_table':  'Douyin'
            }
        ),
        migrations.CreateModel(
            name='ReqeustsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='贴吧标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容详情')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='发帖用户')),
                ('reviewer', models.CharField(blank=True, max_length=255, null=True, verbose_name='审核人')),
                ('last_comment_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='最新评论时间')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='最新评论内容')),
            ],
            options={
                'verbose_name': '贴吧数据',
                'verbose_name_plural': '贴吧数据',
                'db_table': 'ReqeustsData',
            },
        ),
    ]
