# Generated by Django 3.1.7 on 2024-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences', models.CharField(blank=True, max_length=255, null=True, verbose_name='语料')),
                ('labels', models.CharField(blank=True, choices=[('正面情绪', '正面情绪'), ('负面情绪', '负面情绪')], max_length=10, null=True, verbose_name='情绪')),
            ],
            options={
                'verbose_name': '训练集',
                'verbose_name_plural': '训练集',
                'db_table': 'List',
            },
        ),
        migrations.AlterModelOptions(
            name='douyin',
            options={'verbose_name': '抖音MSG', 'verbose_name_plural': '抖音MSG'},
        ),
        migrations.AlterModelOptions(
            name='reqeustsdata',
            options={'verbose_name': '贴吧MSG', 'verbose_name_plural': '贴吧MSG'},
        ),
        migrations.AddField(
            model_name='douyin',
            name='labels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='情绪标识'),
        ),
        migrations.AddField(
            model_name='reqeustsdata',
            name='labels',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='情绪标识'),
        ),
        migrations.AlterField(
            model_name='colect',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reqeustsdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
